version: '3'

volumes:
    db:
        external: false

networks:
  sta-project-network:
    external: true

services:
  back:
    image: ambientum/php:8.1-nginx
    container_name: back
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    networks:
      - sta-project-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    platform: linux/x86_64
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
        - "MYSQL_DATABASE=database"
        - "MYSQL_USER=user"
        - "MYSQL_PASSWORD=secret"
        - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
    networks:
      - sta-project-network
