version: '3.8'

networks:
  sta-project-network:
    external: true

services:
  back:
    image: ambientum/php:8.1-nginx
    container_name: back
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    networks:
      - sta-project-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    platform: linux/x86_64
    volumes:
      - .:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
    networks:
      - sta-project-network